[package]
name = "simwars5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unic-ucd-category = "0.9.0"
unicode-bidi = "0.3.8"

[dependencies.soyo]
path = '..\soyo'
